% PDF for Development Team Feature Development Sub. Module
function [png] = dev_team_fd_submodule_pdf()

% Name of the Module
png.PN_name = 'DevSubModule1';

% set of places
png.set_of_Ps = {'pTasksBuffer', 'pDoing', 'pCommitted', 'pCodeReviewDone', 'pResult'};

% set of transitions
png.set_of_Ts = {'tToDoingState', 'tToCommittedState' , ...
    'tJuniorWork', 'tMiddleWork', 'tConsultantWork', 'tTechLeadWork', ...
    'tJuniorCodeFix', 'tMiddleCodeFix', 'tConsultantCodeFix', 'tTechLeadCodeFix', ...
    'tCodeReview', 'tToToBeTestedState', ...
    'tTasksInput', 'tTasksForTest'};

%set of arcs
png.set_of_As = { 'tTasksInput', 'pTasksBuffer', 1, 'pTasksBuffer', 'tToDoingState', 1, ...
    'tToDoingState', 'pDoing', 1, ...
    'pDoing', 'tToCommittedState', 1, 'tToCommittedState', 'pCommitted', 1, ...
    'pDoing', 'tJuniorWork', 1, 'tJuniorWork', 'pDoing', 1, ...
    'pDoing', 'tMiddleWork', 1, 'tMiddleWork', 'pDoing', 1, ...
    'pDoing', 'tConsultantWork', 1, 'tConsultantWork', 'pDoing', 1, ...
    'pDoing', 'tTechLeadWork', 1, 'tTechLeadWork', 'pDoing', 1, ...
    'pCommitted', 'tCodeReview', 1, 'tCodeReview', 'pCodeReviewDone', 1, ...
    'pCodeReviewDone', 'tToToBeTestedState', 1, 'tToToBeTestedState', 'pResult', 1, ...
    'pResult', 'tTasksForTest', 1, ...
    'pCodeReviewDone', 'tJuniorCodeFix', 1, 'tJuniorCodeFix', 'pCommitted', 1, ...
    'pCodeReviewDone', 'tMiddleCodeFix', 1, 'tMiddleCodeFix', 'pCommitted', 1, ...
    'pCodeReviewDone', 'tConsultantCodeFix', 1, 'tConsultantCodeFix', 'pCommitted', 1, ...
    'pCodeReviewDone', 'tTechLeadCodeFix', 1, 'tTechLeadCodeFix', 'pCommitted', 1, ...
    };

% input/output ports
png.set_of_Ports = {'tTasksInput', 'tTasksForTest'};
end