function [png] = imc_pdf()

png.PN_name = 'IMC';                % NAME OF THE MODULE
png.set_of_Ps = {'pSupportReqBuffer', 'pSupportRespBuffer', ...
    'pPMSprintInBuffer', 'pPMSprintOutBuffer', ...
    'pTBuff', 'pRTBuffer', ...
    'pToTestBuffer', 'pTestedBuffer'};        % SET OF PLACES
png.set_of_Ts = {};                 % SET OF TRANSITIONS

% SET OF ARCS
png.set_of_As = {'tSTeamOut','pSupportReqBuffer', 1, 'pSupportReqBuffer','tDevRequests',1, ...
    'tDevResponses','pSupportRespBuffer', 1, 'pSupportRespBuffer','tSTeamIn', 1, ...
    'tPMOut', 'pPMSprintInBuffer', 1, 'pPMSprintInBuffer', 'tDevInitSprint', 1, ...
    'tDevOutSprint', 'pPMSprintOutBuffer', 1, 'pPMSprintOutBuffer', 'tPMIn', 1, ...
    'tDevTasksAssigned', 'pTBuff', 1, 'pTBuff', 'tTasksInput', 1, ...
    'tTasksForTest', 'pRTBuffer', 1, 'pRTBuffer', 'tReadyForTest', 1, ...
    'tDevTestOut', 'pToTestBuffer', 1, 'pToTestBuffer', 'tQaIn', 1, ...
    'tQaOut', 'pTestedBuffer', 1, 'pTestedBuffer', 'tDevTestIn', 1 };
